services:
  flask-app:
    build:
      context: .
    container_name: flask-app
    networks:
      - app-network
    expose:
      - "5000"
    restart: always

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"  # HTTPS
      - "81:81"    # Panel de administración de Nginx Proxy Manager
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt

networks:
  app-network:
    driver: bridge
